import { Validators } from '@angular/forms';
import { IInputFieldPlayer } from '../../models/inputFields/InputsPlayer';

export const inputsFieldPlayer: IInputFieldPlayer[] = [
  {
    typeComponent: 'input',
    label: 'Nome Completo',
    inputFieldId: 'nome_atleta',
    inputFieldName: 'name',
    inputType: 'text',
    placeholder: 'Digite o nome completo do atleta',
    validators: [Validators.required],
    initialValues: '',
  },
  {
    typeComponent: 'input',
    label: 'Data de Nascimento',
    inputFieldId: 'data_nascimento',
    inputFieldName: 'birth_date',
    inputType: 'date',
    placeholder: '',
    validators: [Validators.required],
    initialValues: '',
  },
  {
    typeComponent: 'input',
    label: 'Número da Camisa',
    inputFieldId: 'numero_camisa',
    inputFieldName: 'shirt_number',
    inputType: 'number',
    placeholder: 'Digite o número da camisa',
    validators: [Validators.required, Validators.min(1), Validators.max(99)],
    initialValues: '',
  },
  {
    typeComponent: 'input',
    label: 'Foto do Atleta (Opcional)',
    inputFieldId: 'foto',
    inputFieldName: 'photo',
    inputType: 'file',
    placeholder: 'Selecione uma foto',
    validators: [],
    initialValues: '',
    accept: 'image/*',
  },
  {
    typeComponent: 'select',
    label: 'Posição',
    inputFieldId: 'posicao',
    inputFieldName: 'position',
    options: [
      { value: '', label: 'Selecione a posição' },
      { value: 'goleiro', label: 'Goleiro' },
      { value: 'defensor', label: 'Defensor' },
      { value: 'meio-campo', label: 'Meio-campo' },
      { value: 'atacante', label: 'Atacante' },
    ],
    validators: [Validators.required],
    initialValues: '',
  },
  {
    typeComponent: 'select',
    label: 'Equipe',
    inputFieldId: 'equipe',
    inputFieldName: 'team',
    options: [
      { value: '', label: 'Selecione a equipe' },
      { value: 'equipe_a', label: 'Equipe A' },
      { value: 'equipe_b', label: 'Equipe B' },
      { value: 'equipe_c', label: 'Equipe C' },
    ],
    validators: [Validators.required],
    initialValues: '',
  },
];
