import { Validators } from '@angular/forms';
import { IGeneralFields } from '../../models/GeneralFieldsInputs';

export const generalInputsAddress: IGeneralFields[] = [
  {
    typeComponent: 'input',
    label: 'CEP',
    inputFieldId: 'cep',
    inputFieldName: 'cep',
    inputType: 'text',
    placeholder: 'Ex: 01000-000',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-4 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'Endereço',
    inputFieldId: 'street',
    inputFieldName: 'street',
    inputType: 'text',
    placeholder: 'Ex: Rua das Palmeiras',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-8 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'Número',
    inputFieldId: 'numberHome',
    inputFieldName: 'number_home',
    inputType: 'number',
    placeholder: '123',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-3 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'Bairro',
    inputFieldId: 'neighborhood',
    inputFieldName: 'neighborhood',
    inputType: 'text',
    placeholder: '123',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-3 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'Cidade',
    inputFieldId: 'city',
    inputFieldName: 'city',
    inputType: 'text',
    placeholder: '123',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-3 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'Estado',
    inputFieldId: 'state',
    inputFieldName: 'state',
    inputType: 'text',
    placeholder: 'São Paulo',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-3 col-sm-12',
  },
];
