import { Validators } from '@angular/forms';
import { IGeneralFields } from '../../models/GeneralFieldsInputs';

export const inputsFieldPlayer: IGeneralFields[] = [
  {
    typeComponent: 'input',
    label: 'Nome Completo',
    inputFieldId: 'nome_completo',
    inputFieldName: 'name',
    inputType: 'text',
    placeholder: 'Ex: João da Silva',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12',
  },
  {
    typeComponent: 'input',
    label: 'Apelido',
    inputFieldId: 'apelido',
    inputFieldName: 'surname',
    inputType: 'text',
    placeholder: 'Ex: Joãozinho',
    validators: [],
    initialValues: '',
    colClass: 'col-12 col-md-4 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'CPF',
    inputFieldId: 'cpf',
    inputFieldName: 'cpf',
    inputType: 'text',
    placeholder: '000.000.000-00',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-4 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'RG',
    inputFieldId: 'rg',
    inputFieldName: 'rg',
    inputType: 'text',
    placeholder: '00.000.000-0',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-4 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'E-mail',
    inputFieldId: 'email',
    inputFieldName: 'email',
    inputType: 'email',
    placeholder: 'Ex: user@reccos.com',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-6 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'Telefone',
    inputFieldId: 'telefone',
    inputFieldName: 'phone',
    inputType: 'tel',
    placeholder: 'Ex: (11) 99999-9999',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-6 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'Data de Nascimento',
    inputFieldId: 'data_nascimento',
    inputFieldName: 'birth_date',
    inputType: 'date',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-6 col-sm-12',
  },
  {
    typeComponent: 'select',
    label: 'Sexo',
    inputFieldId: 'gender',
    inputFieldName: 'gender',
    options: [
      { value: 'masculino', label: 'Masculino' },
      { value: 'feminino', label: 'Feminino' },
    ],
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 col-md-6 col-sm-12',
  },
];
