import { Validators } from '@angular/forms';
import { IGroupedFields } from '../../models/generals/GeneralFieldsInputs';

export const inputsFieldLeagues: IGroupedFields = {
  personalInfo: [
    {
      typeComponent: 'input',
      label: 'League Name:',
      inputFieldName: 'name',
      inputType: 'text',
      placeholder: 'Ex: National League',
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col-12 md:col-6',
    },
    {
      typeComponent: 'input',
      label: 'Location:',
      inputFieldName: 'location',
      inputType: 'text',
      placeholder: 'Ex: Batatais',
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col-12 md:col-4',
    },
  ],
  dates: [
    {
      typeComponent: 'input',
      label: 'Start Date:',
      inputFieldName: 'dt_start',
      inputType: 'date',
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col-12 md:col-6',
    },
    {
      typeComponent: 'input',
      label: 'End Date:',
      inputFieldName: 'dt_end',
      inputType: 'date',
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col-12 md:col-6',
    },
    {
      typeComponent: 'input',
      label: 'Enrollment Start:',
      inputFieldName: 'enrollment_start',
      inputType: 'date',
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col-12 md:col-6',
    },
    {
      typeComponent: 'input',
      label: 'Enrollment End:',
      inputFieldName: 'enrollment_end',
      inputType: 'date',
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col-12 md:col-6',
    },
  ],
  leagueData: [
    {
      typeComponent: 'select',
      label: 'Tournament Format:',
      inputFieldName: 'league_system',
      options: [
        { value: '', label: 'Select tournament format' },
        { value: 'mata-mata', label: 'Knockout' },
        { value: 'pontos_corridos', label: 'Round Robin' },
        { value: 'double_elimination', label: 'Double Elimination' },
        { value: 'round_robin', label: 'Round Robin' },
        { value: 'grupo', label: 'Groups' },
        { value: 'playoffs', label: 'Playoffs' },
      ],
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col',
    },
    {
      typeComponent: 'select',
      label: 'Modality:',
      inputFieldName: 'league_mode',
      options: [
        { value: '', label: 'Select modality' },
        { value: 'caninde', label: 'Canindé' },
        { value: 'futsal', label: 'Futsal' },
        { value: 'areai', label: 'Beach Soccer' },
      ],
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col',
    },
    {
      typeComponent: 'input',
      label: 'Number of Groups:',
      inputFieldName: 'qt_group',
      inputType: 'number',
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col-12 md:col-6',
    },
  ],
  settings: [
    {
      typeComponent: 'input',
      label: 'Number of Teams:',
      inputFieldName: 'num_teams',
      inputType: 'number',
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col-12 md:col-6',
    },
    {
      typeComponent: 'select',
      label: 'Status:',
      inputFieldName: 'status',
      options: [
        { value: '', label: 'Select status' },
        { value: 'active', label: 'Active' },
        { value: 'inactive', label: 'Inactive' },
      ],
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col',
    },
    {
      typeComponent: 'select',
      label: 'Turn:',
      inputFieldName: 'turn',
      options: [
        { value: 's', label: 'Yes' },
        { value: 'n', label: 'No' },
      ],
      validators: [Validators.required],
      initialValues: '',
      colClass: 'col',
    },
  ],
};
