import { Validators } from '@angular/forms';
import { IGeneralFields } from '../../models/generals/GeneralFieldsInputs';

export const generalInputsAddress: IGeneralFields[] = [
  {
    typeComponent: 'input',
    label: 'CEP:',
    inputFieldName: 'cep',
    inputType: 'text',
    placeholder: 'Ex: 01000-000',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 md:col-3',
  },
  {
    typeComponent: 'input',
    label: 'Endereço:',
    inputFieldName: 'street',
    inputType: 'text',
    placeholder: 'Ex: Rua das Palmeiras',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 md:col-7 sm:col-12',
  },
  {
    typeComponent: 'input',
    label: 'Número:',
    inputFieldName: 'number_home',
    inputType: 'number',
    placeholder: '123',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 md:col-2 col-sm-12',
  },
  {
    typeComponent: 'input',
    label: 'Bairro:',
    inputFieldName: 'neighborhood',
    inputType: 'text',
    placeholder: 'Vila Capanema',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 md:col-5',
  },
  {
    typeComponent: 'input',
    label: 'Cidade:',
    inputFieldName: 'city',
    inputType: 'text',
    placeholder: 'São Paulo',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 md:col-5',
  },
  {
    typeComponent: 'input',
    label: 'Estado:',
    inputFieldName: 'state',
    inputType: 'text',
    placeholder: 'SP',
    validators: [Validators.required],
    initialValues: '',
    colClass: 'col-12 md:col-2 sm:col-12',
  },
];
