export const dashAdminMenu = [
  {
    id: 1,
    name: 'Usuários',
    icon: './images/icons/person.svg',
    text: 'Gerenciar usuários',
    router: '/users',
  },
  {
    id: 2,
    name: 'Federações',
    icon: './images/icons/federation.svg',
    text: 'Gerenciar federações',
    router: '/federations',
  },
  {
    id: 3,
    name: 'Ligas',
    icon: './images/icons/league.svg',
    text: 'Gerenciar ligas',
    router: '/leagues',
  },
  {
    id: 4,
    name: 'Times',
    icon: './images/icons/team.svg',
    text: 'Gerenciar times',
    router: '/teams',
  },
  {
    id: 5,
    name: 'Estádios',
    icon: './images/icons/stadium.svg',
    text: 'Gerenciar estádios',
    router: '/stadiums',
  },
  {
    id: 6,
    name: 'Atletas',
    icon: './images/icons/player.svg',
    text: 'Gerenciar atletas',
    router: '/players',
  },
  {
    id: 7,
    name: 'Árbitros',
    icon: './images/icons/refree.svg',
    text: 'Gerenciar arbitros',
    router: '/refree',
  },
  {
    id: 8,
    name: 'Contratos',
    icon: './images/icons/contract.svg',
    text: 'Gerenciar atletas e clubes',
    router: '/contracts',
  },
];
